/*
 * exchangerate-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.InlineResponse200Motd;
import org.openapitools.client.model.InlineResponse200Rates;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-05T14:56:51.155752+08:00[Asia/Manila]")
public class InlineResponse200 {
  public static final String SERIALIZED_NAME_MOTD = "motd";
  @SerializedName(SERIALIZED_NAME_MOTD)
  private InlineResponse200Motd motd;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Boolean success;

  public static final String SERIALIZED_NAME_BASE = "base";
  @SerializedName(SERIALIZED_NAME_BASE)
  private String base;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private String date;

  public static final String SERIALIZED_NAME_RATES = "rates";
  @SerializedName(SERIALIZED_NAME_RATES)
  private InlineResponse200Rates rates;


  public InlineResponse200 motd(InlineResponse200Motd motd) {
    
    this.motd = motd;
    return this;
  }

   /**
   * Get motd
   * @return motd
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200Motd getMotd() {
    return motd;
  }


  public void setMotd(InlineResponse200Motd motd) {
    this.motd = motd;
  }


  public InlineResponse200 success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getSuccess() {
    return success;
  }


  public void setSuccess(Boolean success) {
    this.success = success;
  }


  public InlineResponse200 base(String base) {
    
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getBase() {
    return base;
  }


  public void setBase(String base) {
    this.base = base;
  }


  public InlineResponse200 date(String date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getDate() {
    return date;
  }


  public void setDate(String date) {
    this.date = date;
  }


  public InlineResponse200 rates(InlineResponse200Rates rates) {
    
    this.rates = rates;
    return this;
  }

   /**
   * Get rates
   * @return rates
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public InlineResponse200Rates getRates() {
    return rates;
  }


  public void setRates(InlineResponse200Rates rates) {
    this.rates = rates;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.motd, inlineResponse200.motd) &&
        Objects.equals(this.success, inlineResponse200.success) &&
        Objects.equals(this.base, inlineResponse200.base) &&
        Objects.equals(this.date, inlineResponse200.date) &&
        Objects.equals(this.rates, inlineResponse200.rates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(motd, success, base, date, rates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    sb.append("    motd: ").append(toIndentedString(motd)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

