/*
 * exchangerate-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.InlineResponse200;
import org.openapitools.client.model.InlineResponse2001;
import org.threeten.bp.LocalDate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.deca.gateway.curexrate.ApiException;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Your GET endpoint
     *
     * Historical rates are available for most currencies all the way back to the year of 1999. You can query the API for historical rates by appending a date (format YYYY-MM-DD) to the base URL.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDateTest() throws ApiException {
        LocalDate date = null;
        String base = null;
        String symbols = null;
        String amount = null;
        String paramCallback = null;
        String places = null;
        String format = null;
        String source = null;
                InlineResponse200 response = api.getDate(date, base, symbols, amount, paramCallback, places, format, source);
        // TODO: test validations
    }
    
    /**
     * Your GET endpoint
     *
     * Get the latest foreign exchange reference rates. Latest endpoint will return exchange rate data updated on daily basis.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLatestTest() throws ApiException {
        String base = null;
        String symbols = null;
        String amount = null;
        String paramCallback = null;
        String places = null;
        String format = null;
        String source = null;
                InlineResponse200 response = api.getLatest(base, symbols, amount, paramCallback, places, format, source);
        // TODO: test validations
    }
    
    /**
     * Your GET endpoint
     *
     * API comes with a constantly updated endpoint returning all available currencies. To access this list, make a request to the API&#39;s symbols endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSymbolsTest() throws ApiException {
        String paramCallback = null;
        String format = null;
                InlineResponse2001 response = api.getSymbols(paramCallback, format);
        // TODO: test validations
    }
    
}
